### ISSUE TITLE
Deprecates in symfony 7.1.1

### ISSUE THREAD

**Issue by thenerka1** [Tomsgu/PDFMergerBundle#9]
Deprecation message:

The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Tomsgu\PdfMergerBundle\DependencyInjection\TomsguPdfMergerExtension".

**Comment by Tomsgu** [comment]
We were extending a wrong class the whole time it seems. I just corrected it in https://github.com/Tomsgu/PDFMergerBundle/pull/10.
I am not aware of any break since the `Symfony\Component\DependencyInjection\Extension\Extension` class was already present in Symfony 4, but if there is any please let me know.
